---
title: "시각화 경진대회"
author: "choi"
date: '2020 10 6 '
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(readxl)
```



```{r}
sessionInfo()
```
```{r}
readr::guess_encoding("data/Samsungcard.csv", n_max = 100)
```

```{r}

samsung_card <- read_xlsx("data/Samsungcard.xlsx")
```

```{r}
head(samsung_card)
```
```{r}
shinhancard <- read_xlsx("data/Shinhancard.xlsx")
```
```{r}
head(shinhancard)
```

```{r}
shinhancard <- shinhancard %>% 
  select(-c(6:8))
```

```{r}
head(shinhancard)
```

```{r}
gin_8a <- read_csv("data/GIN00008A.csv")
```
```{r}
gin_9a <- read_csv("data/GIN00009A.csv")
```
```{r}
glimpse(gin_8a)
```
```{r}
glimpse(gin_9a)
```
```{r}
library(jsonlite)
```
```{r}
GIN_10m <- fromJSON("data/center_GIN00010M.json")
```
```{r}
glimpse(GIN_10m)
```
```{r}
readr::guess_encoding("data/Mcorporation/KDX시각화경진대회_SSC_DATA.csv")
```
```{r}
ssc_data <- read_csv("data/Mcorporation/KDX시각화경진대회_SSC_DATA.csv", locale = locale("ko", encoding = "EUC-KR"))
```
```{r}
glimpse(ssc_data)
```
```{r}
files <- list.files(path = "data/Mcorporation/상품 카테고리 데이터_KDX 시각화 경진대회 Only", pattern = "*.xlsx", full.names = T)

```


```{r}
products <- sapply(files, read_excel, simplify=FALSE) %>% 
  bind_rows(.id = "id")
```
```{r}
glimpse(products)
```

```{r}
library(ggplot2)
```

```{r}
cat_rev <- products %>%
  group_by(카테고리명) %>% 
  summarise(mean = mean(구매금액)) %>% 
  arrange(desc(mean))

```
```{r}
cat_rev <- cat_rev[order(cat_rev$mean, decreasing = TRUE), ]
```
```{r}
cat_rev$카테고리명 <- factor(cat_rev$카테고리명, levels = cat_rev$카테고리명)
```

```{r}
head(cat_rev)
```


```{r}
ggplot(cat_rev %>% head(20), aes(x = 카테고리명, y = mean)) + 
  geom_bar(stat="identity", width=.5, fill="tomato3") + 
  theme(axis.text.x = element_text(angle=65, vjust=0.6)) + 
  labs(title="Ordered Bar Chart", 
       subtitle="카테고리명 Vs Avg. 구매금액", 
       caption="source: products")
```

```{r}
cat_rev2 <- products %>%
  group_by(고객나이) %>% 
  summarise(mean = mean(구매금액)) %>% 
  arrange(desc(mean))

```
```{r}
cat_rev <- cat_rev[order(cat_rev$mean, decreasing = TRUE), ]
```


```{r}
category_list <- cat_rev$카테고리명
category_list
```
```{r}
temp_products <- sample_n(products, 1000)
g <- ggplot(temp_products, aes(x = 구매수, y = 구매금액))

```

```{r}
temp_products <- sample_n(products, 1000)

g <- ggplot(temp_products, aes(x = 구매수, y = 구매금액)) 
```

```{r}
g + geom_point(aes(colour = 고객성별)) + 
  scale_x_log10() + 
  scale_y_log10() + 
  labs(subtitle="products: count vs revenue ", 
       y="revenue", 
       x="count", 
       title="Counts Plot")
```

```{r}
g <- ggplot(temp_products, aes(x = 구매수, y = 구매금액))

g + geom_point(col="tomato3") + 
  scale_x_log10() + 
  scale_y_log10() + 
  facet_grid(고객성별 ~.) + 
  labs(subtitle="products: count vs revenue ", 
       y="revenue", 
       x="count", 
       title="Counts Plot")
```


```{r}
gender_products <- products %>% 
  filter(고객성별 != "없음")

dim(products); dim(gender_products)
```

```{r}
temp_products <- sample_n(gender_products, 1000)
g <- ggplot(temp_products, aes(x = 구매수, y = 구매금액))
# g + geom_count(col="tomato3", show.legend=F) +
g + geom_point(col="tomato3") + 
  scale_x_log10() + 
  scale_y_log10() + 
  facet_grid(고객성별 ~.) + 
  labs(subtitle="products: count vs revenue ", 
       y="revenue", 
       x="count", 
       title="Counts Plot")
```
```{r}
cat_rev <- products %>%
  group_by(카테고리명, 고객성별) %>% 
  summarise(mean = mean(구매금액)) %>% 
  arrange(desc(mean)) 
```
```{r}
glimpse(cat_rev)
```
```{r}
cat_rev <- cat_rev[order(cat_rev$mean, decreasing = TRUE), ]

cat_rev
```

```{r}
cat_rev2 <- cat_rev %>% 
  filter(고객성별 != "없음")

```
```{r}
cat_rev2
```

```{r}
ggplot(cat_rev2, aes(x = 카테고리명, y = mean, fill = 고객성별)) +
  geom_bar(stat="identity", position = "dodge", width=.5)
```

```{r}
i = 1
j = i+7
category_list <- as.character(category_list)

cat_rev2 %>% 
  filter(카테고리명 %in% category_list[c(i:as.numeric(i+7))]) %>% 
  ggplot(aes(x = 카테고리명, y = mean, fill = 고객성별)) +
  geom_bar(stat="identity", position = "dodge", width=.5) + 
  theme(axis.text.x = element_text(angle=65, vjust=0.6)) + 
  labs(title="Ordered Bar Chart", 
       subtitle="카테고리명 Vs Avg. 구매금액 by 고객성별", 
       caption="source: products")
```


```{r}
category_graph <- function(df, cat_list = cat_list) {category_list <- sort(as.character(cat_list))
  
  print(category_list)
  for (i in seq(1, 64, by = 8)) {
    i = i
    j = i+7
    plot <- df %>% 
      filter(카테고리명 %in% category_list[i:j]) %>% 
      ggplot(aes(x = 카테고리명, y = mean, fill = 고객성별)) +
      geom_bar(stat="identity", position = "dodge", width=.5) + 
      theme(axis.text.x = element_text(angle=65, vjust=0.6)) + 
      labs(title="Ordered Bar Chart",
           subtitle="카테고리명 Vs Avg. 구매금액 by 고객성별", 
           caption="source: products")
    
    print(plot)
  }
}

category_graph(cat_rev2, category_list)
```


```{r}
economics$returns_perc <- c(0, diff(economics$psavert)/economics$psavert[-length(economics$psavert)])
```


```{r}
ggplot(economics, aes(x=date)) + 
  geom_line(aes(y=returns_perc)) + 
  labs(title="Time Series Chart", 
       subtitle="Returns Percentage from 'Economics' Dataset", 
       caption="Source: Economics", 
       y="Returns %")
```

```{r}
glimpse(economics)
```
```{r}
class(economics$date)
```

```{r}
temp_date <- "20200110"
conv_date <- as.Date(temp_date, format = "%Y%m%d")
print(conv_date)
```
```{r}
class(conv_date)
```

```{r}
glimpse(shinhancard)
```
```{r}
shinhancard$일별 <- as.Date(shinhancard$일별, format = "%Y%m%d")
```
```{r}
glimpse(shinhancard)
```

```{r}
ggplot(shinhancard, aes(x=일별)) + 
  geom_line(aes(y=`카드이용건수(천건)`)) + 
  labs(title="Time Series Chart", 
       subtitle="Returns Percentage from 'Economics' Dataset", 
       caption="Source: Economics", 
       y="Returns %")
```
```{r}
shinhancard %>% 
  filter(일별 == "2019-01-01") %>% 
  dim()
```

```{r}
shinhancard %>% 
  rename(date = "일별") %>% 
  group_by(date) %>% 
  summarise(mean = mean(`카드이용건수(천건)`)) %>% 
  ggplot(aes(x=date)) + 
  geom_line(aes(y=mean)) + 
  theme(axis.text.x = element_text(angle=65, vjust=0.6)) + 
  labs(title="Time Series Chart", 
       subtitle="Avg. Sales from 'Shinhan Card' Dataset", 
       caption="Source: Shinhan Card", 
       y="Avg. Sales (1000)") + 
  theme_bw()
```

```{r}
shinhancard %>% 
  rename(date = "일별", gender = "성별") %>%    
  group_by(date, gender) %>% 
  summarise(mean = mean(`카드이용건수(천건)`)) %>% 
  ggplot(aes(x=date)) + 
  geom_line(aes(y=mean, colour = gender)) + 
  labs(title="Time Series Chart", 
       subtitle="Avg. Sales from 'Shinhan Card' Dataset", 
       caption="Source: Shinhan Card", 
       y="Avg. Sales (1000)")
```
```{r}
shinhancard %>% 
  rename(date = "일별") %>%  
  group_by(date, 연령대별) %>% 
  summarise(mean = mean(`카드이용건수(천건)`)) %>% 
  ggplot(aes(x=date)) + 
  geom_line(aes(y=mean, colour = 연령대별)) + 
  labs(title="Time Series Chart", 
       subtitle="Avg. Sales from 'Shinhan Card' Dataset", 
       caption="Source: Shinhan Card", 
       y="Avg. Sales (1000)")
```

